### ISSUE TITLE
Error Handling Support

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/js-holder-sdk#21]
### Hypothesis
It would be really great to have a helper class or function(s) that could generate all of the valid errors in the CDR standards

### Description
This would be an addition to the SDK to generate a well formed JSON structure for each of the error types in the CDR standards.  Could also include a function that generates an error payload from an array of errors.

### Available Options
Option suggested above

**Comment by tom-schier** [comment]
Merged
