### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/js-holder-sdk#22]
### Hypothesis
Pagination is a repeatable, but relatively complex, aspect of the standards.  It would be good to have support for this

### Description
Functions to:
- parse `page` and `page-size` for validity
- create pagination links
- handle pagination errors

### Available Options
Could be a series of functions, a middleware or a single function (or a combination)

**Comment by tom-schier** [comment]
@JamesMBligh  We are planning to include some of this in the next release, similar to what is in  [this](https://github.com/ConsumerDataStandardsAustralia/mock-data-holder-nodejs/blob/master/test-data-server/src/utils/paginate-data.ts) file .

**Comment by tom-schier** [comment]
Merged
